version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  open-assistant-service:
    container_name: open-assistant-service
    build: ./open-assistant-service
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
  nlp:
    container_name: nlp
    build: nlp
    restart: always
    ports:
      - "5000:5000"
    expose:
      - 5000
  telegram-bot-service:
    container_name: telegram-bot-service
    build: telegram-bot-service
    restart: always
    ports:
      - "8082:8082"
    expose:
      - 8082
